library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
text <- readLines("script.txt") 
docs <- Corpus(VectorSource(text))
toSpace <-content_transformer(function(x,pattern) gsub(pattern,"",x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs,removeWords, stopwords("english"))
docs <- tm_map(docs, removeWords, c("blabla1","blabla2"))
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, stripWhitespace)
dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
c <- data.frame(freq=v)
d <- data.frame(word = names(v), freq=v)
r <- head(c,10)

first <- rgb(255/255, 31/255, 61/255, 1)
third <- rgb(91/255, 227/255, 227/255, 1)
fourth <- rgb(253/255, 255/255, 241/255, 1)
second <- rgb(229/255, 225/255, 56/255, 1)

palvec <- c(fourth=fourth, third=third, second=second, first=first)